directories:
  output: dist_electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
appId: mshahrani.shuffler.app
productName: shuffler
icon: ./src/assets/icon.png
target: win
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
publish:
  provider: github
  owner: Dr. Mohammed Alshahrani
  vPrefixedTagName: true
  token: <stripped sensitive data>
  private: true
  publishAutoUpdate: true
electronVersion: 3.0.13
